# Generated by Django 4.2.5 on 2023-09-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_cours_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
